### ISSUE TITLE
Move tool configurations to a separate package

### ISSUE THREAD

**Issue by hedgepigdaniel** [respond-framework/rudy#10]
Things like babel, eslint, jest configs and the like could be moved to a separate package. Besides being cleaner, this would make it practical for client apps to reuse them.

**Comment by faceyspacey** [comment]
During this phase, it's **far easier** if *ALL* the tests run as if it's one giant package. Possibly undo Lerna, or definitely dont add any additional packages. The primary thing is you guys understand the intent of every line of code. When I return I'll have something to say about organization and process. 

There's a lot of reasoning behind the way I had it, but the main one is ease of use. It's far easer to install just `rudy` than have to install many packages. *And* if you import from `rudy/link` webpack will only incorporate the link package if it's used. The need for separate packages is what much of the industry does, but not all of the industry. It's overrated. It makes our work harder because now we gotta deal with cascading changes and dependency issues, and it makes it harder for our users, as they gotta deal with more than one package, etc. 

Lerna offers you guys minimal value right now since this stuff isnt even published to NPM, and shouldnt be until I return and cosign it.

**Comment by faceyspacey** [comment]
Ps. Really glad to have u on board in this capacity Daniel!! Don’t take what I’m saying too harshlly. Just consider it, and proceed according to your pre-existing flow. All can be resolved. The main thing is just code and features, not organization and process just yet. But I understand if u work better with things whipped into shape according to ur current workflow. The intent was to upgrade the workflow for the product at the end, and until then develop in the easiest atmosphere, which was that of a single package. We may have a ways to go, so let’s not jump the gun. I’ll be back shortly. With enough hands to bring this into the mainstream, this will sure to make a major splash, as it will correct a glitch in history (handling effects within render nodes) that has been costing developers enormous amounts of time.

**Comment by hedgepigdaniel** [comment]
Hi James!

It's great to hear from you, and great to hear and see that you are helping out. Definitely happy to have your criticism, we'll be better for it.

**Comment by hedgepigdaniel** [comment]
Re the specific things you mentioned:

I'm not sure if/when you've tried lerna, but I've found its very convenient. You retain the convenience of having everything in one repository, one set of branches, one build system, etc. So there is no need to build other packages after each code change and use `yarn link` or whatever - its still just one big repository with everything in it where if you change some code everything updates and works. I think we could improve the dev experience for other packages like RUC and BPUI if they were in this repository aswell (lerna has a nice command to replay the commit history in a subdir) - it would be easier to test changes in them, e.g. by using the boilerplate. You can do all of that while still publishing entirely separate packages, with separate dependencies, etc.

Lerna handles the versioning pretty automatically. Basically as long as you follow conventional commits spec, it automatically finds which packages a commit touches, and increments the appropriate version number in that package and its dependents based on the commit message. At the moment the versioning is "independent" (separate versions for each package), but we could easily change it to central versioning (one version for all packages). Maybe that's simpler.

As far as users are concerned, they only need to install the packages they directly use. So factoring things out of the core into multiple packages doesn't mean users have to keep track of them - all they need is `@rudy/router` - it can depend on the other packages as necessary. The link component is the only one that's different in that sense (the core doesn't depend on it) - but it could easily be depended on and re exported by the core. I thought it should be separate because i depends on react. I figured since the whole point of all this is to stop overloading non-rendering concerns onto react, why should the core package depend on it? IMO it should be simple to swap out react for vue or whatever else people want (If its a pure function, how hard can it be). Maybe in the future there could be a `@rudy/vue-link` similar to `@rudy/react-link`

**Comment by hedgepigdaniel** [comment]
Re tests, not sure if you followed but Zack and I had a conversation about it here: https://github.com/respond-framework/rudy/pull/5#discussion_r230624538

I think that talk I posted is really 200% worth watching. Like, he goes way to far, but I think he makes alot of good points. I still think integration tests are useful, they just solve a different problem. They give you a rough idea if everything is hooked up right to solve a higher level task without having to individually test every detail. All the integration tests are still there, and we've made sure they are passing (I spent a bunch of time fixing up a crash because the global random number generator monkey patch was making `source-map-support` crash somewhere very deep). I'm trying to add some unit tests aswell so that as we go forward we can have a higher guarantee of correctness and easier debugging when tests fail.

**Comment by hedgepigdaniel** [comment]
That makes sense. For me its alot less intimidating to look at a small separate package and be immediately confident that I understand its interface with the rest of the code. Similar for 3rd party middleware authors, I think it will help to be able to point them to a package and say "This is what a middleware looks like, you can copy this to get started". Lerna/workspaces have improved alot recently, so I hope they start to look less intimidating and don't get in the way. Definitely let me know if you find anything that's bad for DX - I'll do my best to fix it up. You don't need to run any `lerna` commands to set up a dev environment btw, just the standard `yarn && yarn run start` or whatever script you want (see [HACKING](https://github.com/respond-framework/rudy/blob/master/HACKING.md)). It doesn't matter what package you run `yarn` in either - wherever you run it from it just works, installs all the deps for the whole repo.

Maybe a better compromise is to have unit tests with bigger units. As you say, if there's a bunch of pure functions calling each other then testing them all at once is still simple in terms of configuration (no state, dependencies, etc, so no need to do any monkey patching, dependency injection, or the like). At the same time, the tests aren't quite so tightly coupled to the exact structure of modules/functions, so its less effort to do small refactors without having to also update tests. I'll give wallaby a go.
