### ISSUE TITLE
expose unconnected Link component

### ISSUE THREAD

**Issue by reaysawa** [respond-framework/rudy#22]
Reading

https://github.com/respond-framework/rudy/blob/master/packages/link/src/index.jsx#L191

Seems like it's not possible to have access to the unconnected Link component.

Reason: I'm using another library to connect to the store since React-Redux doesn't seem to support hooks yet. I want to try to setup my own connection using the unconnected component.

**Comment by hedgepigdaniel** [comment]
If you want to make a PR to export the unconnected one, I think that's a good idea.

In this case - is the underlying problem that Rudy is using an old version of `react-redux`? Perhaps if we upgrade that it will fix the problem.

**Comment by reaysawa** [comment]
From what I've read, the react-redux team is still figuring out how to deal with hook components, so even updating to the newest version wouldn't solve it.

When I gave this some more thought, I don't know if it makes sense to expose the unconnected component alone, since NavLink and the mapToState function are both still needed for proper usage. And if it's to expose and decouple the internal functions so that people can plug their own, then it wouldn't make sense to rely on react-redux - but if the rest of the rest of the library does, making a change in that direction feels weird to me.

I'm considering just using the dispatch functions alone or editing the component as an internal package until the react-redux stuff gets sorted out. But if you think it's fine to just expose everything needed to connect, I could try submitting a PR.

**Comment by hedgepigdaniel** [comment]
Its not too hard to make a bare bones `<Link />` yourself - at its most basic its a component that renders an anchor tag with a URL and has a click handler that dispatches a redux action instead if it is called. So if you want to make one yourself I think that will work fine, and you can handle your own connection to redux. At the moment there's probably too many props being passed into `<Link />` that it doesn't actually need, which might complicate using `LinkInner` on its own.

Not sure what you mean by the rest of the library, but AFAIK the only part of rudy that depends on React or react-redux is the link component (its tightly coupled to Redux, bot not React). Its possible to publish LinkInner and Link as separate packages and only have Link depend on react-redux. That might be beneficial in this case seeing as `react-redux` is a peer dependency, and we wouldn't want to warn users only using the unconnected component to install react-redux.

I wouldn't object to that, although you're the first person I've heard from who is trying to move away from react-redux in particular
