### ISSUE TITLE
BrowserHistory console.log statements

### ISSUE THREAD

**Issue by Guria** [respond-framework/rudy#46]
I have 2 questions regarding this statements.
https://github.com/respond-framework/rudy/blob/master/packages/rudy/src/history/BrowserHistory.js#L221
https://github.com/respond-framework/rudy/blob/master/packages/rudy/src/history/BrowserHistory.js#L246

1. Could we remove them, not to pollute console in production.
2. Sometimes it logs several times in a row. Is it expected behavior?

**Comment by hedgepigdaniel** [comment]
Sure, PR welcome.

@faceyspacey would know best, but it looks to me like its expected - for some reason chrome does not synchronously update the location when using the pushState API.
