### ISSUE TITLE
Going forward/back multiple steps in the browser causes incorrect location state

### ISSUE THREAD

**Issue by hedgepigdaniel** [respond-framework/rudy#59]
To reproduce in the boilerplate (in a single tab)
1. Navigate to the app (localhost:3000)
1. Use internal links to travel a number of steps though the app, e.g. home -> redux -> home -> react. The location state how has for example 4 entries, and the `index` (current entry) is 3.
1. Navigate to an external site using the browser address bar. The sequence of entries in the history is now:
    1. new tab
    1. entry 0: /
    1. entry 1: /list/redux
    1. entry 2: /
    1. entry 3: /list/react
    1. external site
1. Use the browser back button to go all the way to the first entry for the app (home, the first time it was visited).

At this point
- in a browser supporting session storage (`supportsSession` returns true), the restored history state has all 4 entries, but the `index` is wrong. It is `3` (the last page visited, the react page) rather than `0` (the homepage). The UI displays a mixture of the homepage and the react page.
- in a browser not supporting session storage (`supportsSession` returns false), the current entry is correct, but there is only the first entry. Pressing the forward button now triggers an error that there is no state to pop to.

**Comment by hedgepigdaniel** [comment]
I don't see why one couldn't reproduce this also by clicking the back button multiple times - if you did it fast enough, the JS that updates the `index` in session storage might not run

**Comment by faceyspacey** [comment]
It seems you fixed some key stuff in the history mirroring I was worried about and needed to further test.  How solid is it? How's it now that you have fixed some things? Is there any remaining bugs in history mirroring?

**Comment by hedgepigdaniel** [comment]
It works pretty solidly as far as I can tell. I suspect there is some inconsistency with the pre change route callbacks since the browser APIs ultimately don't let us know whether the future stack entries are within the same session or a different session/site. But the basic stuff is reliable - back/next buttons and links always go to the right place, and the callbacks always work if the past/future stack entries are in the same session.

**Comment by faceyspacey** [comment]
Cool...Got another question for ya: how many people/companies do you think are using your version of Respond in production? 1-10? 10-20? 20+?
