### ISSUE TITLE
About hash tag in URL

### ISSUE THREAD

**Issue by ragnaroksj** [respond-framework/rudy#62]
Hi Teams,
I notice Rudy support hash feature. I want to implement the feature that like http://localhost:3000/list#test-hash, and then the browser will jump to the section. 
I download the boilerplate and try to play around it. But the feature is not working. I post the code here.
<Link
      role="link"
      tabIndex="0"
      to={{ type: 'LIST', params: { category: 'redux' }, hash: 'test-hash' }}
    >
      Redux with hash
</Link>

And I add a tag in the file: src/components/List.js with following code:
<a name="test-hash">Test-hash</a>

I am very new to this one and I think I might miss something. Could you help me with this one?

Thank you.

**Comment by hedgepigdaniel** [comment]
Hi,

What you're talking about will be implemented as part of scroll restoration. I'm actually working on it right now (see the `feat/scroll-restoration` branch: https://github.com/respond-framework/rudy/compare/feat/scroll-restoration?expand=1), I hope to get it out soon.

Will post here once its out

**Comment by ragnaroksj** [comment]
Thank you very much :)
